version: '3.7'

services:
  db:
    image: mongo:4.2.3-bionic
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./db_data/mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - ./db_data/mongodb:/data/db
      - ./db_data/mongoconfig:/data/configdb
    networks:
      - myLocalNet
  redis:
    image: redis:7-alpine
    volumes:
      - ./db_data:/data/redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ABC@123
    ports:
      - '6379:6379'
    networks:
      - myLocalNet
volumes:
  db_data:
networks:
  myLocalNet:
    driver: bridge